"""activities

Revision ID: ab1287056126
Revises: 6c3dfc1fb2d4
Create Date: 2024-11-23 12:17:30.762802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1287056126'
down_revision = '6c3dfc1fb2d4'
branch_labels = None
depends_on = None


def upgrade():
    # Create tables without foreign keys first
    op.create_table('comments',
        sa.Column('id', sa.Integer(), primary_key=True),
        # ... other columns ...
    )
    
    op.create_table('posts',
        sa.Column('id', sa.Integer(), primary_key=True),
        # ... other columns ...
    )
    
    # Now add foreign keys in a separate migration or after creating the tables
    # op.create_foreign_key('fk_comment_post', 'comments', 'posts', ['post_id'], ['id'])
    # op.create_foreign_key('fk_post_comment', 'posts', 'comments', ['comment_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activity_post_id', type_='foreignkey')
        batch_op.drop_constraint('fk_activity_comment_id', type_='foreignkey')
        batch_op.drop_column('comment_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
