"""activities

Revision ID: ab1287056126
Revises: 6c3dfc1fb2d4
Create Date: 2024-11-23 12:17:30.762802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1287056126'
down_revision = '6c3dfc1fb2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_activity_post_id', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_activity_comment_id', 'comment', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activity_post_id', type_='foreignkey')
        batch_op.drop_constraint('fk_activity_comment_id', type_='foreignkey')
        batch_op.drop_column('comment_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
